<?php

/**
 * @file
 * The Everyday Tools module was created to house functions that are useful in every Drupal build that requires
 * some degree of development. 
 * The functions in this module are for Site Performance
 *
 */

/**
* Check the pages load time
* Usage $loadtime = new loadTime();
*/
class everyday_tools_loadTime{
  private $time_start = 0;
  private $time_end = 0;
  private $time = 0;
  
  public function __construct() {
    $this->time_start= microtime(true);
  }
  
  public function __destruct(){
    $this->time_end = microtime(true);
    $this->time = ($this->time_end - $this->time_start);
    echo '<div class="loadTime">Loaded in ' . $this->time . ' seconds</div>';
  }
}
